on:
  push:
    branches:
      - masterbranch 




jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: "login Docker hub"
        run: docker login --username maiaboelmagd --password dckr_pat_kYGWi5CfAgNZ0l04s1V1-maH5hc
         



